class Constants:
    LOGGING_CONFIG = 'config/logging_config.ini'

    CONFIG_SECTION_CONNECTOR = 'CONNECTOR'
    CONFIG_SECTION_POLLER = 'POLLER'
    CONFIG_SECTION_PARSER = 'PARSER'
    CONFIG_SECTION_SENDER = 'SENDER'
    CONFIG_SECTION_TRANSACTION_HANDLER = 'TRANSACTION_HANDLER'

    CONFIG_CONNECTOR_NAME = 'Name'
    CONFIG_CONNECTOR_HOST = 'Host'
    CONFIG_CONNECTOR_PORT = 'Port'

    CONFIG_POLLER_CLASS = 'Class'
    CONFIG_POLLER_ARGS = 'Args'
    CONFIG_POLLER_MIN_THREADS = 'MinThreads'
    CONFIG_POLLER_MAX_THREADS = 'MaxThreads'

    CONFIG_PARSER_CLASS = 'Class'
    CONFIG_PARSER_ARGS = 'Args'
    CONFIG_PARSER_MIN_THREADS = 'MinThreads'
    CONFIG_PARSER_MAX_THREADS = 'MaxThreads'

    CONFIG_SENDER_CLASS = 'Class'
    CONFIG_SENDER_ARGS = 'Args'
    CONFIG_SENDER_MIN_THREADS = 'MinThreads'
    CONFIG_SENDER_MAX_THREADS = 'MaxThreads'

    CONFIG_TRANSACTION_HANDLER_CLASS = 'Class'
    CONFIG_TRANSACTION_HANDLER_ARGS = 'Args'

    EVENT_POLLED = 'POLLED'
    EVENT_PARSED = 'PARSED'
    EVENT_SEND = 'SEND'
    EVENT_DONE = 'DONE'
    EVENT_ERROR = 'ERROR'
